language: python
branches:
  only:
  - master
  - develop
  - feature/buildci
python:
  - "3.7"

jobs:
  include:
    - stage: PyPI Release Develop
      script: skip
      deploy: &pipy
        provider: pypi
        user: "__token__"
        server: https://test.pypi.org/legacy/
        distributions: "sdist bdist_wheel"
        password: $PIPY_TOKEN
        on:
          branch: feature/buildci
      after_deploy:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL
      if: type = push
    - stage: Tests, Lint and Coverage
      name: "Environment Setup"
      script:
        - flake8
        - python -m pytest --cov
      if: type = pull_request