language: python
branches:
  only:
  - master
  - develop
python:
  - "3.7"

jobs:
  include:
    - stage: Tests, Lint and Coverage
      name: "Lint Flake8"
      script: pipenv run flake8
    -
      name: "Unit Tests"
      script: pipenv run python -m pytest --cov
    - stage: PyPI Release Develop
      before_deploy:
        - python setup.py sdist bdist_wheel
      deploy:
        provider: pypi
        user: "__token__"
        file:
        - dist/*.whl
        - dist/*.tar.gz
        server: https://test.pypi.org/legacy/
        password: $PIPY_TOKEN
        on:
          branch: develop
          condition: $TRAVIS_EVENT_TYPE = push
      after_deploy:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL


install:
  - pip install pipenv
  - pipenv install --dev
