language: python
branches:
  only:
  - master
  - develop
  - feature/buildci
python:
  - "3.7"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

jobs:
  include:
    - stage: Tests, Lint and Coverage
      name: "Environment Setup"
      script:
        - pipenv run flake8
        - pipenv run python -m pytest --cov
      if: type = pull_request
    - stage: PyPI Release Develop
      before_deploy: pipenv shell
      deploy:
        provider: pypi
        user: "__token__"
        server: https://test.pypi.org/legacy/
        distributions: "sdist bdist_wheel"
        password: $PIPY_TOKEN
      if: branch = feature/buildci AND type = push
      after_deploy:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL

install:
  - pip install pipenv
  - pipenv install --dev