language: python
branches:
  only:
  - master
  - develop
  - /^v.*$/
  - /^d-.*$/
python:
  - "3.7"
cache: pipenv

install:
  - pip install pipenv
  - pipenv install --dev

jobs:
  include:
    - stage: PyPI Release Develop
      script: skip
      deploy: &pipy
        skip_cleanup: true
        provider: pypi
        user: "__token__"
        server: https://test.pypi.org/legacy/
        distributions: "sdist bdist_wheel"
        password: $PIPY_TOKEN
        on:
          tags: true
          condition: "$TRAVIS_TAG =~ ^d-.*$"
      after_deploy:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL

    - stage: PyPI Release Production
      script: skip
      deploy: &pipy
        skip_cleanup: true
        provider: pypi
        user: "__token__"
        distributions: "sdist bdist_wheel"
        password: $PIPY_TOKEN
        on:
          tags: true
          condition: "$TRAVIS_TAG =~ ^v.*$"
      after_deploy:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL

    - stage: Tests, Lint and Coverage
      name: "Environment Setup"
      script:
        - pipenv run flake8
        - pipenv run python -m pytest --cov
      if: type = pull_request
